### ISSUE TITLE
Regarding  undefined reference to `__cxa_atexit' Error

### ISSUE THREAD

**Issue by jaehongyoon** [pillowlab/StepRampMCMC#2]
Hi, I followed the README instructions and pasted -lstdc++ to the CXXLIBS options but I did not resolve the issue. I'm currently using R2015a with CUDA 8.0. Did anyone encounter the same error? Thanks,

**Comment by jaehongyoon** [comment]
This is what I get from the verbose mode.

kcSetDevice


**************************************************************************
  Warning: Neither -compatibleArrayDims nor -largeArrayDims is selected. 
           Using -compatibleArrayDims. In the future, MATLAB will require
           the use of -largeArrayDims and remove the -compatibleArrayDims
           option. For more information, see:
           http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html
**************************************************************************

-> mexopts.sh sourced from directory (DIR = .)
   FILE = /home/ryan/neuron_model/StepRampMCMC/code/CUDAlib/mexopts.sh
----------------------------------------------------------------
->    MATLAB                = /usr/local/MATLAB/R2015a
->    CC                    = gcc
->    CC flags:
         CFLAGS             = -ansi -D_GNU_SOURCE  -fexceptions -fPIC -fno-omit-frame-pointer -pthread
         CDEBUGFLAGS        = -g
         COPTIMFLAGS        = -O -DNDEBUG
         CLIBS              = -Wl,-rpath-link,/usr/local/MATLAB/R2015a/bin/glnxa64 -L/usr/local/MATLAB/R2015a/bin/glnxa64 -lmx -lmex -lmat -lm -lstdc++
         arguments          =  -DMX_COMPAT_32
->    CXX                   = g++
->    CXX flags:
         CXXFLAGS           = -ansi -D_GNU_SOURCE -fPIC -fno-omit-frame-pointer -pthread
         CXXDEBUGFLAGS      = -g
         CXXOPTIMFLAGS      = -O -DNDEBUG
         CXXLIBS            = -Wl,-rpath-link,/usr/local/MATLAB/R2015a/bin/glnxa64 -L/usr/local/MATLAB/R2015a/bin/glnxa64 -lmx -lmex -lmat -lm -lstdc++
         arguments          =  -DMX_COMPAT_32
->    FC                    = gfortran
->    FC flags:
         FFLAGS             = -fexceptions -fbackslash -fPIC -fno-omit-frame-pointer
         FDEBUGFLAGS        = -g
         FOPTIMFLAGS        = -O
         FLIBS              = -Wl,-rpath-link,/usr/local/MATLAB/R2015a/bin/glnxa64 -L/usr/local/MATLAB/R2015a/bin/glnxa64 -lmx -lmex -lmat -lm
         arguments          =  -DMX_COMPAT_32
->    LD                    = g++
->    Link flags:
         LDFLAGS            = -pthread -shared -Wl,--version-script,/usr/local/MATLAB/R2015a/extern/lib/glnxa64/mexFunction.map -Wl,--no-undefined
         LDDEBUGFLAGS       = -g
         LDOPTIMFLAGS       = -O
         LDEXTENSION        = .mexa64
         arguments          =  -lstdc++ -L/usr/local/cuda-8.0//lib64/ -lcuda -lcudart -lnppc -lnpps -lnppi -lcusparse -lcublas -lcurand -lmwblas
->    LDCXX                 = 
->    Link flags:
         LDCXXFLAGS         = 
         LDCXXDEBUGFLAGS    = 
         LDCXXOPTIMFLAGS    = 
         LDCXXEXTENSION     = 
         arguments          =  -lstdc++ -L/usr/local/cuda-8.0//lib64/ -lcuda -lcudart -lnppc -lnpps -lnppi -lcusparse -lcublas -lcurand -lmwblas
----------------------------------------------------------------


Warning: You are using gcc version "4.8.4".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

-> g++ -O -pthread -shared -Wl,--version-script,/usr/local/MATLAB/R2015a/extern/lib/glnxa64/mexFunction.map -Wl,--no-undefined -o  "/home/ryan/neuron_model/StepRampMCMC//code/CUDAlib/mex/kcSetDevice.mexa64"   "/home/ryan/neuron_model/StepRampMCMC//code/CUDAlib/obj/kcSetDevice.o"  -lstdc++ -L/usr/local/cuda-8.0//lib64/ -lcuda -lcudart -lnppc -lnpps -lnppi -lcusparse -lcublas -lcurand -lmwblas -Wl,-rpath-link,/usr/local/MATLAB/R2015a/bin/glnxa64 -L/usr/local/MATLAB/R2015a/bin/glnxa64 -lmx -lmex -lmat -lm -lstdc++

/usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS): In function `atexit':
(.text+0x12): undefined reference to `__cxa_atexit'
collect2: error: ld returned 1 exit status

    mex: link of ' "/home/ryan/neuron_model/StepRampMCMC//code/CUDAlib/mex/kcSetDevice.mexa64"' failed.

Unable to complete successfully.

**Comment by jaehongyoon** [comment]
Found the answer from the following link.

https://cn.mathworks.com/matlabcentral/answers/107762-mex-link-of-mexgpuexample-mexa64-failed#answer_169213

The trick is to append '-lc' to mex compile options.

**Comment by latimerk** [comment]
Thanks for letting us know and posting the solution!
This error might depend on the Matlab version. I couldn't recreate it with CUDA 8.0 with R2017a.
